services:
  db:
    image: mysql:latest
    container_name: Prueba-Tecnica-Delto
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Prueba-Tecnica-Delto
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: